import { access, readFile, writeFile } from "fs/promises";
import { join } from "node:path";

import type { CommitType, MerlinConfig } from "../types/index.js";
import { DEFAULT_CONFIG } from "../utils/constants.js";

type CommitlintRule = [number, string, unknown];
type CommitlintRules = Record<string, CommitlintRule>;

// "js-merlin" = generated by merlin's init wizard (safe to regenerate)
// "js-custom"  = user-authored JS (cannot safely rewrite)
type CommitlintConfigFormat = "json" | "js-merlin" | "js-custom" | "yaml";

export type DetectedCommitlintConfig = {
    filePath: string;
    format: CommitlintConfigFormat;
};

export type SyncResult = {
    success: boolean;
    filePath: string;
    appliedRuleNames: string[];
    manualInstructions?: string;
};

// Priority order mirrors commitlint's own file lookup: first match wins.
// JS entries are initially "js-custom" and reclassified after a content check.
const CONFIG_FILE_CANDIDATES: Array<{
    fileName: string;
    format: CommitlintConfigFormat;
}> = [
    { fileName: ".commitlintrc", format: "json" },
    { fileName: ".commitlintrc.json", format: "json" },
    { fileName: ".commitlintrc.yaml", format: "yaml" },
    { fileName: ".commitlintrc.yml", format: "yaml" },
    { fileName: ".commitlintrc.js", format: "js-custom" },
    { fileName: ".commitlintrc.cjs", format: "js-custom" },
    { fileName: ".commitlintrc.mjs", format: "js-custom" },
    { fileName: "commitlint.config.js", format: "js-custom" },
    { fileName: "commitlint.config.cjs", format: "js-custom" },
    { fileName: "commitlint.config.mjs", format: "js-custom" },
];

export async function detectCommitlintConfig(
    repoRoot: string
): Promise<DetectedCommitlintConfig | null> {
    for (const candidate of CONFIG_FILE_CANDIDATES) {
        const filePath = join(repoRoot, candidate.fileName);

        try {
            await access(filePath);
        } catch {
            continue;
        }

        let { format } = candidate;
        if (format === "js-custom") {
            const content = await readFile(filePath, "utf-8");
            if (isMerlinGeneratedJsConfig(content)) {
                format = "js-merlin";
            }
        }
        return { filePath, format };
    }
    return null;
}

export function buildSyncRules(config: Required<MerlinConfig>): CommitlintRules {
    const rules: CommitlintRules = {
        "subject-max-length": [2, "always", config.maxSubjectLength],
        "scope-max-length": [2, "always", config.maxScopeLength],
    };

    // Only add type-enum when the user has deviated from the default types.
    // The @commitlint/config-conventional preset already enforces the default 11 types,
    // so adding an explicit rule would be redundant noise - and would break if the
    // upstream preset ever adds a new type that merlin's snapshot doesn't include.
    if (hasCustomTypes(config.types)) {
        const typeValues = config.types.map((commitType: CommitType) => commitType.value);
        rules["type-enum"] = [2, "always", typeValues];
    }

    return rules;
}

export async function syncToCommitlintConfig(
    config: Required<MerlinConfig>,
    repoRoot: string
): Promise<SyncResult> {
    const detected = await detectCommitlintConfig(repoRoot);

    if (!detected) {
        return { success: false, filePath: "", appliedRuleNames: [] };
    }

    const rules = buildSyncRules(config);
    const appliedRuleNames = Object.keys(rules);

    if (detected.format === "json") {
        await syncToJsonConfig(detected.filePath, rules);
        return { success: true, filePath: detected.filePath, appliedRuleNames };
    }

    if (detected.format === "js-merlin") {
        await regenerateMerlinJsConfig(detected.filePath, rules);
        return { success: true, filePath: detected.filePath, appliedRuleNames };
    }

    // yaml or js-custom: cannot safely rewrite, return manual instructions instead
    return {
        success: false,
        filePath: detected.filePath,
        appliedRuleNames: [],
        manualInstructions: buildManualInstructions(rules),
    };
}

// Marker written at the top of every JS config merlin generates or syncs.
// Its presence on a subsequent sync means the file is still merlin-owned and safe to regenerate.
const MERLIN_MANAGED_MARKER = "// @merlin-managed";

function isMerlinGeneratedJsConfig(content: string): boolean {
    // File was previously synced by merlin (has the ownership marker)
    const hasMerlinMarker = content.includes(MERLIN_MANAGED_MARKER);
    // File is the initial extends-only template from merlin's setup wizard (no rules yet)
    const isInitialTemplate =
        content.includes("@commitlint/config-conventional") &&
        !content.includes("rules:");
    return hasMerlinMarker || isInitialTemplate;
}

function hasCustomTypes(types: CommitType[]): boolean {
    const defaultValues = new Set(
        DEFAULT_CONFIG.types.map((commitType) => commitType.value)
    );
    if (types.length !== defaultValues.size) return true;
    return types.some((commitType) => !defaultValues.has(commitType.value));
}

async function syncToJsonConfig(filePath: string, rules: CommitlintRules): Promise<void> {
    const rawContent = await readFile(filePath, "utf-8");
    const parsed = JSON.parse(rawContent) as Record<string, unknown>;
    const existingRules = (parsed.rules as CommitlintRules) ?? {};
    parsed.rules = { ...existingRules, ...rules };
    await writeFile(filePath, `${JSON.stringify(parsed, null, 4)}\n`, "utf-8");
}

async function regenerateMerlinJsConfig(
    filePath: string,
    rules: CommitlintRules
): Promise<void> {
    await writeFile(filePath, generateJsConfigContent(rules), "utf-8");
}

function generateJsConfigContent(rules: CommitlintRules): string {
    const ruleLines = Object.entries(rules)
        .map(
            ([name, [severity, applicability, value]]) =>
                `        "${name}": [${severity}, "${applicability}", ${formatRuleValue(value)}],`
        )
        .join("\n");

    return [
        MERLIN_MANAGED_MARKER,
        `export default {`,
        `    extends: ["@commitlint/config-conventional"],`,
        `    rules: {`,
        ruleLines,
        `    },`,
        `};`,
        ``,
    ].join("\n");
}

function buildManualInstructions(rules: CommitlintRules): string {
    const ruleLines = Object.entries(rules)
        .map(
            ([name, [severity, applicability, value]]) =>
                `    "${name}": [${severity}, "${applicability}", ${formatRuleValue(value)}]`
        )
        .join(",\n");

    return `Add these rules to your commitlint config's "rules" section:\n{\n  "rules": {\n${ruleLines}\n  }\n}`;
}

function formatRuleValue(value: unknown): string {
    if (Array.isArray(value)) {
        return `[${(value as string[]).map((item) => `"${item}"`).join(", ")}]`;
    }
    return String(value);
}
